.github/workflows/check.yml
CHANGELOG.md
Cargo.toml
src/lib.rs
src/systems.rs

Add CI checks for all feature sets and platforms

---

src/transform_node.rs

fixes compilation on bevy master

add BufferMapMode to map_buffer

---

src/lib.rs

better error message for missing ctx

---

Cargo.toml
examples/ui.rs

This PR bumps `egui` to version 0.13.0.

Bump egui to 0.13.0

---

CHANGELOG.md
Cargo.toml
src/systems.rs

Fix receiving input when holding a button

---

.github/workflows/check.yml
Cargo.toml
examples/two_windows.rs
examples/ui.rs

upgrade egui v0.15

---

Cargo.toml
src/lib.rs
src/systems.rs

Switch to arboard for managing clipboard

---

.github/workflows/check.yml
examples/two_windows.rs
examples/ui.rs
src/lib.rs
src/render_systems.rs

Track Egui texture ids internally

---

.github/workflows/check.yml
Cargo.toml
examples/side_panel.rs

https://user-images.githubusercontent.com/2943388/154870413-d5086e28-5f0e-493b-bc8d-1eada0f57a65.mov

Add side panel example

---

src/systems.rs

We can avoid the `collect` calls here

Avoid allocations by utilizing `HashMap::iter_mut`.

---

src/egui.wgsl
src/egui_node.rs

Fix color blending for user textures

---

examples/ui.rs

Added demonstration how to use `egui::Window::open(self, &'open mut bool)`. Since I am a newcomer to rust I have been struggling with passing a mutable bool. Should be useful for other newcomers as well since closing or opening a window is such a common use case.
Hope that helps.

Window is open and checkbox is checked added to ui.rs example

---

CHANGELOG.md
Cargo.toml
README.md
examples/ui.rs
src/systems.rs

- Fixed an example to support the new textureFilter feature
- fixed `egui::FullOutput`'s requests for repaints
- updated changelog
- Bumped version

update to support egui 0.19.0

---

examples/two_windows.rs
src/lib.rs
src/render_systems.rs

Make it so all windows support rendering egui output by default.

Implement better multi-window support

---

src/render_systems.rs

This fixes https://github.com/mvlabat/bevy_egui/issues/194 for me

Add `add_srgb_suffix` to fix #194 for WASM

---

.github/workflows/check.yml
Cargo.toml
README.md
src/systems.rs

Reopened https://github.com/mvlabat/bevy_egui/pull/230/

Update egui to 0.24

---

examples/ui.rs

Clean up text describing Central Panel

Minor text cleanup in ui example

---

.github/workflows/check.yml
Cargo.toml
src/lib.rs

Custom render

---

README.md

I saw there was a couple of places in the README to be updated.

Update README.md for bevy 0.13

---

src/web_clipboard.rs

Adapt to `web-sys` clipboard api change

---

Cargo.toml
examples/paint_callback.rs
examples/render_egui_to_texture.rs
src/egui_node.rs
src/egui_render_to_texture_node.rs
src/lib.rs
src/render_systems.rs
src/systems.rs

An attempt to merge paint callback support into #299
This PR won't cover input handling, that is more likely to land with Bevy 0.15.

Initial world space UI support

---

Cargo.toml
README.md
src/input.rs
src/lib.rs
src/text_agent.rs

Fix clipboard error handling, wasm clipboard and logs

---

Cargo.toml
examples/color_test.rs
examples/ui.rs
src/output.rs

hiii!
i'm not sure if i'm doing this right. i tested it my app at least and clipboard and url opening are working there

update to egui 0.31

---

Cargo.toml
README.md
examples/color_test.rs
examples/paint_callback.rs
examples/render_egui_to_image.rs
examples/render_to_image_widget.rs
examples/run_manually.rs
examples/side_panel_3d.rs
examples/simple_multipass.rs
examples/two_windows.rs
examples/ui.rs
src/egui_node.rs
src/helpers.rs
src/input.rs
src/lib.rs
src/output.rs
src/render_systems.rs
src/text_agent.rs
src/web_clipboard.rs

all examples behave identically as before in my testing :3

update to bevy 0.16

---

src/lib.rs

Fix the panic when closing a window
