vladbat00/bevy_egui

src/egui_node.rs
I was trying to load image textures other than the sample `icon.png`, and I kept getting this error:
```
thread 'main' panicked at 'copy would end up overruning the bounds of one of the buffers or textures', /Users/will/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:35
stack backtrace:
0: rust_begin_unwind
at /rustc/80184183ba0a53aa4f491753de9502acd3d6920c/library/std/src/panicking.rs:493:5
1: std::panicking::begin_panic_fmt
at /rustc/80184183ba0a53aa4f491753de9502acd3d6920c/library/std/src/panicking.rs:435:5
2: <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::{{closure}}
at /Users/will/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:35
3: …
```
=> Fix texture copying

.github/workflows/check.yml, Cargo.toml, README.md, examples/ui.rs, src/egui_node.rs, src/lib.rs, src/systems.rs, src/transform_node.rs
This shouldn't be merged yet, I'm just putting this up as a draft PR so that anyone who wants to update to bevy main can see that the work is already done.
includes #3
=> update to bevy 0.5

CHANGELOG.md, README.md, examples/simple.rs, examples/two_windows.rs, examples/ui.rs, src/egui_node.rs, src/lib.rs, src/systems.rs, src/transform_node.rs
=> Multiple windows support

README.md, examples/simple.rs, examples/two_windows.rs, examples/ui.rs, src/egui_node.rs, src/lib.rs, src/systems.rs, src/transform_node.rs
builds on top of #12
[Diff only to #12](https://github.com/jakobhellermann/bevy_egui/compare/bevy-0.5...jakobhellermann:multiple-windows)
Changes:
- `&egui_context.ctx` -> `egui_context.ctx()`
- new `egui_context.ctx_for_window(window_id)` for drawing to another window
- [`egui::setup_pipeline`](https://github.com/jakobhellermann/bevy_egui/blob/c30710c18daa2abfb93d0bd6ad5f547c297d9a56/src/lib.rs#L429) and `egui::RenderGraphConfig` which needs to get run for additional windows
- `Egui{Shapes, Output, Input}` -> `HashMap<WindowId, Egui{Shapes, Output, Input}>`
Let me know what you think :smile:
=> Support for multiple windows

examples/ui.rs
Hi!
I've found that in ui.rs one import is missing - I've got compilation errors on my local machine when I've copy&pasted the example.
New import resolves the issue.
=> Fix an example

src/egui_node.rs, src/systems.rs
=> Fix crashes related to invalid scissor or window size

src/lib.rs
This is necessary for bevy-inspector-egui to support multiple windows. Could you maybe release a small non-breaking version so that I can implement this without waiting for the next big release?
=> add `try_ctx_for_window` function

src/egui_node.rs, src/lib.rs
The code had a few double references that `clippy` was complaining about. This PR gets rid of them, and thus gets rid of all `clippy` warnings.
=> Clippy fixes

Cargo.toml, examples/ui.rs, src/egui_node.rs, src/lib.rs, src/systems.rs
Covers making bevy_egui compile and that's about it. I didn't add `Event::Zoom` from the [egui changelog](https://github.com/emilk/egui/blob/master/CHANGELOG.md)
=> Update egui to 1.16.1

src/lib.rs, src/render_systems.rs, src/systems.rs
I implemented support for [headless mode](https://github.com/bevyengine/bevy/pull/3439) that now available in 0.6. I just basically removed some unwraps.
This makes it easier to test systems that use egui.
=> Add headless mode support

src/lib.rs
should fix #52 
@Hilku can you confirm by putting
```toml
[patch.crates-io]
bevy_egui = { git = "https://github.com/jakobhellermann/bevy_egui", branch = "after-ui-pass" }
```
in your `Cargo.toml`?
=> run egui pass after `bevy_ui`

src/egui_node.rs
Fixes #57.
Checks the window bounds before setting the scissor rect.
=> Fix wgpu crash on minimizing window

.github/workflows/check.yml, Cargo.toml, README.md, src/lib.rs
=> Add `multi_threaded` feature as passthrough to avoid needing separate egui dependency.

README.md
Megaui is deprecated and links back to this project.
=> Remove link to megaui

src/lib.rs
Found another link to `megaui`, which is deprecated and links back to `bevy_equi`, making it not useful.
=> Remove megaui reference from lib.rs docs

Cargo.toml, examples/ui.rs, src/egui.wgsl, src/egui_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs
Closes https://github.com/mvlabat/bevy_egui/issues/74
Closes https://github.com/mvlabat/bevy_egui/pull/75
I haven't yet figured out how to do a partial texture update (using https://docs.rs/wgpu/0.12.0/wgpu/struct.CommandEncoder.html#method.copy_buffer_to_texture), so instead I opted to store the full image, update part of it, and then recreate the full texture.
=> Update to egui 0.17

src/lib.rs
I added this function because `add_image` requires `mut` and sometimes it inconvenient because you can't use it inside `show`.
=> Add a funtion to get image id

src/lib.rs
I wrapped the returned id into `egui::TextureId` since it usable only in this context. Just for consistency with other methods.
=> Return egui::TextureId on removal

Cargo.toml, src/systems.rs
This fixes hyperlinks opening in a new tab whether modifiers are pressed or not.
There is still an issue: opening a hyperlink in a new tab, then coming back to the previous tab, will leave the modifier keys pressed even if they've been released in the meantime. But I believe this is an issue with bevy and not bevy_egui.
=> new_tab support on open_url

Cargo.toml, examples/side_panel.rs, examples/two_windows.rs, examples/ui.rs, src/egui.wgsl, src/egui_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs
This needs a more thorough review. But it looks like the examples are working, and it's working in at least one of my projects.
=> Update to work with bevy main (and eventually 0.8)

Cargo.toml
=> Add feature to disable egui builtin fonts

src/systems.rs
=> Fix releasing buttons when outside of a window

Cargo.toml, examples/render_to_image_widget.rs, examples/side_panel.rs, examples/two_windows.rs, examples/ui.rs, src/egui_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs
One of my projects has a rendering bug that is fixed on Bevy/main. Due to breaking changes in `0.9 dev`, I couldn't use bevy_egui anymore. This PR adopts all the bevy changes required to run bevy_egui with the current state of bevy 0.9 dev. Not sure if you already want to merge it, but I wanted to share it already in case anybody else is in my situation.
=> update to bevy 0.9 dev

src/systems.rs
This fixes a Windows specific problem:
Currently windows created by bevy with bevy_egui installed show the default cursor icon when hovering over the edges of the window, although a resize cursor icon for window resizing should be shown instead. 
This was implemented in a similar fashion to how `egui-winit` handles this problem, see [here](https://github.com/emilk/egui/blob/367378d75dcc1670418ce464cb1aafa4c8b2387b/crates/egui-winit/src/lib.rs#L614).
Probably partially fixes #126.
=> Fix window resize cursor icon on Windows

Cargo.toml
This gets rid of `image@0.23.14` in the dependency tree.
[ardboard 0.3 changes](https://github.com/1Password/arboard/blob/master/CHANGELOG.md#changed-3)
=> update arboard dependency

src/egui_node.rs
Fixes #136.
Because of some driver quirks, Bevy will ignore swapchain timeouts on some devices, as mentioned in bevyengine/bevy#5957. When this occurs, `extracted_window.swap_chain_texture` will be `None`.
Bevy handles this by bailing out of the render node early (see [here](https://github.com/bevyengine/bevy/blob/b3d59060db6bbe7c63b227510fd58460e1790dd9/crates/bevy_render/src/camera/camera_driver_node.rs#L81)), and this fix is implemented in the same way.
=> Fix panic due to missing swapchain texture.

CHANGELOG.md, Cargo.toml, src/systems.rs
Only change that affected bevy_egui was the added field to key events: [`egui::Event::Key::repeat`](https://docs.rs/egui/latest/egui/enum.Event.html#variant.Key.field.repeat) which has specific documentation saying integrations should simply set it to false, so it was an easy change.
Egui changelog is here: https://github.com/emilk/egui/blob/master/CHANGELOG.md#0210---2023-02-08---deadlock-fix-and-style-customizability
Tested all the examples and tests on my Windows machine, couldn't find any issues.
=> Update Egui to 0.21

Cargo.toml
I would like to activate the serde feature in egui via bevy_egui. This pull request adds in an optional feature to enable this.
=> Add serde feature

src/systems.rs
I'm building an app where I need users to enter a "at sign" (@), and input text is not allowing me to do that.
Looks like the issue is from bevy_egui.
My changes appear to fix it, but I didn't make a bigger background check on why that condition was there originally.
Other context as to how I ended up to this solution: https://discord.com/channels/691052431525675048/1072569924972728320
=> Fix ctrl or win interfering with character inputs

src/systems.rs
Time in egui is mostly used for animation. These animations should run regardless of whether `Time` is currently paused.
=> pass raw time to bevy_egui

src/lib.rs
`setup_new_windows_system` is added as both a `PreStartup` system and a `PreUpdate` system, and the `Query` will return the same `Added<Window>` for both. For window(s) created on startup, it will run again on the first frame and recreate the components, so any egui setup done with a startup system is lost.
One solution is to have the query omit any entities that already have an EguiContext.
Fixes #160
=> Fix recreation of EguiContext on startup

src/egui_node.rs
In `EguiNode::run`, an attempt is made to fix for bad scissor rect bounds by the width & height of the scissor rect to the physical window.
However, this only works if the scissor rect starts at (0, 0); if it isn't, then the scissor rect may still go out of bounds of the window.
This can cause a panic from wgpu when `window.resolution.set(x, y)` is called from WASM with a resolution *lower* than the current setting, as when the window updates, but the egui draw commands haven't been updated, the scissor rect can extend outside of the render target if it has an offset top-left corner.
This PR changes it so that the scissor rect bound check subtracts the upper left coordinate, ensuring that the scissor rect remains within the bounds of the window even if the draw command doesn't originate …
=> Fix incorrect bounds check for set_scissor_rect

Cargo.toml
bevy_core_pipeline is only used in the render to texture example
=> move `bevy_core_pipeline` to dev-dependencies

src/lib.rs, src/systems.rs
Just a single line of code added to be able to use NumpadEnter. See  [Issue #170](https://github.com/mvlabat/bevy_egui/issues/170).
To get this to compile I did have to change the level of `missing_docs` as the compiler complains of the `WorldQuery` derive macro being undocumented. See bevy [Issue #3492](https://github.com/bevyengine/bevy/issues/3492), the crate `bevy_ecs_macros` is not yet documented enough. Once that is fixed, then the level of documentation can go back up to `deny` (under a separate PR).
=> Accept NumpadEnter as Enter

.github/workflows/check.yml
The following updates are performed:
* update [`actions/cache`](https://github.com/actions/cache) to v3
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
* replace [unmaintained](https://github.com/actions-rs/toolchain/issues/216) `actions-rs/toolchain` by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
* replace unmaintained `actions-rs/cargo` by direct invocation of `cargo`
Still using the outdated / unmaintained actions will generate several warnings in CI runs, for example in https://github.com/mvlabat/bevy_egui/actions/runs/4763363890:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, actions/cache@v2, actions-rs/cargo@v1. For more information see: …
=> Update GitHub Actions CI

src/egui_node.rs, src/lib.rs
Hi, I've moved the sampler descriptor into the EguiSettings, since the hardcoded linear_descriptor is not desirable for pixel perfect usecases. I've also had to implement a compare_descriptors function to keep the PartialEq functionality. The sampler_descriptor can now be set to: 
- (Default) linear and clamping to edge
- (use_nearest_descriptor function) nearest and clamping to edge
- (use_bevy_descriptor function) derived from the bevy ImagePlugin setup
- completely custom
A simple demo. Left is linear, right is nearest.
=> Sampler descriptor moved into EguiSettings

Cargo.toml, examples/render_to_image_widget.rs, examples/two_windows.rs, examples/ui.rs, src/egui_node.rs, src/systems.rs
=> feat: upgrade to egui 0.23.

src/egui_node.rs, src/lib.rs, src/render_systems.rs
This PR simplifies extraction of resources by leveraging the standard `ExtractComponentPlugin` along with the `ExtractCompont` trait: Read more [here](https://docs.rs/bevy_render/latest/bevy_render/extract_component/index.html).
I opted to put `Egui*Textures` in a separate PR (#210), because it was maybe simpler to review
=> Simplify extraction by using derive

src/lib.rs, src/render_systems.rs
Similar to #211, this one opts to use ExtractResource where possible.
=> Use ExtractResource for Egui*Textures

src/lib.rs
This allows manipulating `EguiSettings` in editors/scripts/etc
=> `#[derive(Reflect)]` on `EguiSettings`

.github/workflows/check.yml, Cargo.toml, examples/render_to_image_widget.rs, src/egui_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs
to update cargo when bevy 0.12 is out
=> upgrade to bevy 0.12

README.md
I guess it was forgotten during update.
=> Update Cargo.toml in README.md

src/systems.rs
The predicted_dt should be based on the target framerate and not depend on frame-to-frame fluctuations. Instead, we can pass total elapsed time instead to let egui handle things correctly.
=> Handle giving time input to egui correctly

.github/workflows/check.yml, Cargo.toml, src/lib.rs, src/systems.rs
Closes #198 (and the duplicate I was about to make :0).
arboard dependency does not support android and fails too build for said platform,
this pr modifies the existing target_arch checks too include target_os = "android" check
=> disable manage clipboard for wasm32 AND android

src/systems.rs
The previous implementation seems to have lost track of what the redraw was supposed to be tracking. This meant button clicks would **not** trigger a redraw on `WinitSettings::desktop_app()` (only a mouse move after would cause a redraw).
I've tested this on my own project and things work much more correct!
Fixes #239.
=> Fix requested repaints not causing Bevy to redraw.

Cargo.toml, src/systems.rs
Another attempt to https://github.com/mvlabat/bevy_egui/pull/181
This PR retrieves the user agent for better platform detection.
Not much tested, it seemed on wasm I was receiving physical keys, so my next step is to check how it's going with bevy 0.13
=> Fix @ on AZERTY on wasm

src/systems.rs
Copy, paste, cut, undo, redo and maybe others were bound to WIN instead of CTRL outside of macOS, which was wrong. It broke after updating to the latest Bevy. This pr binds them back to CTRL.
I also have to prevent text input when win is pressed because the command check doesn't work by itself anymore.
I don't have a mac available right now, but I assume it was broken for macOS too, because copy is CMD-C on macOS. The egui docs also tell you to use the same thing for command as mac_cmd.
=> Fix text editing keybinds

src/lib.rs, src/systems.rs, static/error_web_sys_unstable_apis.txt
<details><summary>Before:</summary>
<p>
</p>
</details> 
<details><summary>After:</summary>
<p>
</p>
</details>
=> Better error on Web when missing web_sys_unstable_apis

src/lib.rs, src/systems.rs
Fixes #272. The issue reminded me that Bevy now includes window ids in event payloads. The refactor to use them instead of manual focused window tracking eliminates some buggy edge cases and simplifies a lot of code.
=> Get window ids from events instead of manual tracking

src/lib.rs, src/systems.rs
Hello,
I had this problem that I described at this issue:
- #277
where it is a blocker for my use case that `bevy_egui` sends `RequestRedraw` events, even when I'm not painting any EGUI window.
So, this PR fixes the `process_output_system` so that it doesn't emit that event when nothing is being painted.
It will keep working as usual when EGUI is painting.
----
On another note:
I'm not sure that `RequestRedraw` is really needed. If the `UpdateMode` of the Bevy's `WinitSettings` resource is `UpdateMode::Continuous`, Bevy will redraw anyway. If it is `UpdateMode::Reactive` or `UpdateMode::ReactiveLowPower`, both of them should answer to Window events, like moving the cursor ([see here in bevy_winit](https://github.com/bevyengine/bevy/blob/c593ee1055047a64501efa5de5885c9d85547af3/crates/bevy_ …
=> Request Redraw only if really needed. Fixes #277

examples/render_to_image_widget.rs
Issue https://github.com/bevyengine/bevy/issues/3462 has been fixed. So since Bevy 0.13, render lights can be specified per RenderLayer.
So our example needs to be updated, because right now render pass does not have any light at all.
I've decided to reuse the same light by specifying `RenderLayers::all()`, although adding a separate one (with preview_pass_layer and without) is also fine.
=> fix light in `render_to_image_widget` example

Cargo.toml, build.rs, examples/render_to_image_widget.rs, examples/side_panel.rs, examples/ui.rs, src/egui_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs
=> Update to Bevy 0.14

src/systems.rs
This does the same thing bevy does for the `ButtonInput<KeyCode>` resource here: https://github.com/bevyengine/bevy/blob/d8d49fdd1393ab543a0ed66da9a255fda7d66572/crates/bevy_input/src/keyboard.rs#L151-L155
Fixes https://github.com/mvlabat/bevy_egui/issues/232
I'm not sure why all the fields in `InputEvents` are public, since it makes this a breaking change and isn't required for things to compile.
=> Clear modifier state when focus is lost

Cargo.toml, examples/paint_callback.rs, examples/paint_callback.wgsl, src/egui_node.rs, src/render_systems.rs
Resolves https://github.com/mvlabat/bevy_egui/issues/294
Bevy render graph nodes create render passes, paint callback can not be expanded into a render graph subgraph.
Graph node can contain custom rendering code or, for example, [Render Phase](https://docs.rs/bevy_render/latest/bevy_render/render_phase/index.html) abstraction to render multiple type of resources with multiple render pipelines in the current render pass.
This implementation supports bevy rendering logic with custom render implementation.
For now native wgpu RenderPass can not be used because of the following issue: https://github.com/bevyengine/bevy/issues/13225
=> Paint callback support

src/egui_node.rs, src/egui_render_to_texture_node.rs
Support executing additional render passes or adding command buffers from paint callback
=> Paint callback functionality improvements

src/lib.rs, src/systems.rs
Fixes https://github.com/mvlabat/bevy_egui/issues/145
This is enough for my needs, but FYI:
- `Ime::Disabled` just maps to `Event::CompositionEnd` with an empty string for text. You could capture `Ime::Preedit` as state to handle it that way. I don't know where best to add the state.
=> Basic IME mapping

.github/workflows/check.yml, Cargo.toml, src/egui_node.rs, src/egui_render_to_texture_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs, src/text_agent.rs, src/web_clipboard.rs
`bevy_egui` was causing compilation of our large projects to delay until `bevy`, and more critically, `bevy_pbr` were done compiling. `bevy_pbr` is extremely slow, and depends on `bevy_render`, which is also slow to compile. The result is compilation cannot parallelize well.
This change should be entirely idempotent for users, it simply switches dependencies to the bevy subcrates. The effect of this is that bevy_egui, and anything that depend on it, can now start compiling at the same time as `bevy_pbr`, this had a huge positive effect on compile times in our larger project, because many things depend on `bevy_egui`.
The only "gotcha" here is that I had to depend on `encase` manually, otherwise you end up needing to go through bevy's `ShaderType` derive, which falls over when `bevy` is …
=> Compile time improvement: depend on subcrates

src/lib.rs
When Initial world space UI support (https://github.com/vladbat00/bevy_egui/pull/304) was added, the fallback query for when the render feature is disabled results in `EguiContext`s being added every entity in the scene.
This PR makes it so that `setup_render_to_texture_handles_system` only runs when the render feature is enabled.
=> Don't add EguiContext to every entity when render feature is disabled.

.github/workflows/check.yml, CHANGELOG.md, Cargo.toml, examples/paint_callback.rs, examples/render_egui_to_texture.rs, examples/render_to_image_widget.rs, examples/side_panel.rs, examples/two_windows.rs, examples/ui.rs, src/egui_node.rs, src/egui_render_to_texture_node.rs, src/lib.rs, src/render_systems.rs, src/systems.rs, src/text_agent.rs
Currently testing on bevy 0.15 rc3.
- cursor handling changed, we rely on the new feature `custom_cursor`.
- more info about retained rendering world update: https://github.com/Vrixyz/bevy_egui/pull/5
=> Update to bevy 0.15

CHANGELOG.md, Cargo.toml, examples/ui.rs, src/lib.rs
This commit fixes the broken links to the old github page (before the bevy_egui creator changed their github username).
This should replace the broken links in:
- the library source (src/lib.rs)
- the changelog
- ui example
- Cargo.toml
Any issues let me know!
=> fix dead links to old 'mvlabat' user to new 'vladbat00' user

README.md
Just noticed they were out of date after navigating to one of them via readme link, and finding out that it was not compiling.
=> Update links to examples in README.md

Cargo.toml, examples/absorb_input.rs, src/input.rs, src/lib.rs
Closes #47, #218
- Add `egui_wants_input` run condition
- Add `absorb_bevy_input_system` system (disabled by default, can be enabled with `EguiGlobalSettings::enable_absorb_bevy_input_system`)
=> Implement absorbing inputs and Egui input run condition

Cargo.toml, README.md, examples/absorb_input.rs, examples/color_test.rs, examples/paint_callback.rs, examples/render_egui_to_image.rs, examples/render_to_image_widget.rs, examples/run_manually.rs, examples/side_panel_2d.rs, examples/side_panel_3d.rs, examples/simple.rs, examples/two_windows.rs, examples/ui.rs, src/lib.rs
Rewrite of #370 - observers are fun and games, but this approach seems to work better, since going multi-pass requires less changes now, and it's actually compatible with exclusive systems (which are crucial for bevy-inspector-egui and the likes).
This PR implements an experimental multi-pass mode support.
It doesn't introduce breaking changes apart from `EguiPlugin` receiving a new field: `enable_multipass_for_primary_context`. Even though there are alternative ways to opt-in for the multi-pass mode which don't bring breaking changes in, this was mainly done for the feature discoverability.
Users are encouraged to switch to the multi-pass mode (even though it's experimental for now, I hope the single-pass mode will be eventually phased out), and maintainers of plugins depending on …
=> Implement multipass support (attempt 2, using custom schedules)

Cargo.toml, src/lib.rs
This integrates Bevy's AccessKit setup with egui's AccessKit integration so egui UIs are accessible.
I haven't been able to test this on Linux, where it may not work since accesskit integration is feature-gated there. In theory it should just pull in dependencies and more or less be a no-op since an access technology will never request accessibility, but I can't say for sure and would appreciate help testing.
Thanks!
=> Integrate AccessKit

Cargo.toml
Import the `image` dependency without its default features, for consistency with `bevy_image` and to avoid the `avif` feature which pulls some NCSA license, which is currently not one of the licenses Bevy itself approves. This makes it more consistent with Bevy.
Fixes #379
=> Remove default features from `image` dependency

examples/absorb_input.rs, examples/color_test.rs, examples/file_browse.rs, examples/paint_callback.rs, examples/render_egui_to_image.rs, examples/render_to_image_widget.rs, examples/run_manually.rs, examples/side_panel_2d.rs, examples/side_panel_3d.rs, examples/simple.rs, examples/two_windows.rs, examples/ui.rs, src/lib.rs
This PR deprecates the option to disable the multi-pass mode. Ideally, that's the only mode I'd like to support in `bevy_egui`, as it helps to keep systems organised in a single schedule (`EguiContextPass`), which in turn helps to avoid issues such as #212, makes widgets requiring multiple passes work by default (#358), etc.
Also, I hope that the deprecation will prompt users to report issues with the multi-pass mode if there are any. If there are issues with the multi-pass mode that can't be easily solved or there are any reasons why users want to keep using the single-pass mode (or, for example the `Update` schedule specifically), we'll at least learn of those. (And there's always an option to "un-deprecate" the single-pass mode in that case.)
Having said that, my intention is to keep …
=> Deprecate the option to disable the multi-pass mode
